services:
  # homeassistant:
  #   container_name: homeassistant
  #   image: homeassistant/home-assistant
  #   # build:
  #   #   dockerfile: Dockerfile
  #   volumes:
  #     - ./config1:/config
  #     - /etc/localtime:/etc/localtime:ro
  #     - /run/dbus:/run/dbus:ro
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   cap_add:
  #     - SYS_RAWIO
  #   # devices:
  #   # - '/dev/gpiochip4:/dev/gpiochip4'
  #   # - '/dev/snd:/dev/snd'
  #   # - "/dev/spidev0.0:/dev/spidev0.0"
  #   # network_mode: host
  #   ports:
  #     - 8123:8123
  #   # environment:
  #   #  - NO_COPY=true
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - "./mqtt/config:/mosquitto/config"