# https://www.home-assistant.io/integrations/default_config/
default_config:

 
# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.huffbox: debug

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 172.17.0.0/16
        - 172.16.0.0/12
        - 192.168.0.0/16
      allow_bypass_login: true
    - type: homeassistant
  media_dirs:
    media: /media
  # debug: true
